FROM docker.io/python:3.8

COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 3000
USER nobody

ENV FLASK_APP=src
ENV FLASK_ENV=production
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "3000"]
